version: "3"

services:
  home:
    build:
      context: ./services/home
      args:
        - PUBLIC_URL=/
    networks:
      - test

  product:
    build:
      context: ./services/product
      args:
        - PUBLIC_URL=/product
    networks:
      - test

  gateway:
    build:
      context: ./gateway
    ports:
      - 8080:80
    networks:
      - test
    depends_on:
      - home
      - product

networks:
  test:
